# Generated by Django 3.1.7 on 2021-12-14 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='starting_bid',
            field=models.PositiveIntegerField(),
        ),
    ]
