# Generated by Django 3.1.7 on 2021-12-16 20:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_bidding'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
